# Uses https://github.com/sagiegurari/cargo-make

[config]
# Skip core tasks; they overlap with some of the tasks below
skip_core_tasks = true

[env]
RUSTFLAGS = "--deny warnings"
RUSTDOCFLAGS = "--deny warnings"

# Ideally would run cargo with `--locked` to avoid updating the lockfile in case it is outdated,
# see also https://github.com/rust-lang/cargo/issues/8207
# However, it seems cargo-make itself also implicitly updates the lockfile, so there is no point
# in using `--locked` then for the cargo commands here. Instead the CI workflow runs `git diff`.

# Default features
[tasks.build-default]
command = "cargo"
args = ["build"]

[tasks.test-default]
command = "cargo"
# Important: Don't use `--all-targets` here; that would exclude doctests (see https://github.com/rust-lang/cargo/issues/6669)
args = ["test"]
dependencies = ["build-default"]

# All targets
# This is the only `cargo build ... --all-targets` task here because building all targets
# includes the dev dependencies whose feature selection could affect the main dependencies
[tasks.build-all-targets]
command = "cargo"
args = ["build", "--all-targets"]

[tasks.build]
dependencies = [
    "build-default",
    "build-all-targets",
]

[tasks.test]
dependencies = [
    "test-default",
]

# Note: Running Clippy should hopefully suffice, no need to run `cargo check`, see https://stackoverflow.com/q/57449356
[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "--deny", "warnings"]

[tasks.doc]
command = "cargo"
args = ["doc", "--all-features", "--no-deps"]

[tasks.format-check]
command = "cargo"
# Note: This does not include standalone `/tests/macro_errors/*.rs` files because they are not
# included as modules; would have to run `rustfmt` manually for them, e.g. (with PowerShell)
# `rustfmt --check (Get-Item ./tests/macro_errors/*.rs).FullName`
args = ["fmt", "--all", "--check"]


# Note: 'default' task is called when `cargo make` is used without explicit task name
[tasks.default]
# Dependencies here are ordered by 'severity'; first fail for build errors and eventually
# fail in case of format check errors
dependencies = [
    "build",
    "test",
    "clippy",
    "doc",
    "format-check",
]
