contact_links:
  - name: Usage question & discussion
    url: https://github.com/Marcono1234/markdown-doctest/discussions
    about: Ask usage questions and discuss markdown-doctest in GitHub Discussions.
